spring:
  datasource:
    url: jdbc:postgresql://kindjozsef-example-pg-server.postgres.database.azure.com:5432/postgres
    driverClassName: org.postgresql.Driver
    username: ${pgdbuser1}
    password: ${pgdbpassword1}
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: webapp
  cloud:
    azure:
      keyvault:
        secret:
          endpoint: https://rd-keyvault-12345.vault.azure.net/
          property-source-enabled: true
          property-sources[0]:
            endpoint: https://rd-keyvault-12345.vault.azure.net/
