spring:
  datasource:
    url: jdbc:postgresql://kindjozsef-server.postgres.database.azure.com:5432/kindjozsef-database
    driverClassName: org.postgresql.Driver
    username: ${pgdbuser1}
    password: ${pgdbpassword1}
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: webapp




azure:
  keyvault:
    uri: https://uniquekeyvault123.vault.azure.net/