spring:
  datasource:
    url: jdbc:postgresql://eccdf4d557ee.privatelink.postgres.database.azure.com:5432/kindjozsef2-database
    driverClassName: org.postgresql.Driver
    username: ${pgdbuser1}
    password: ${pgdbpassword1}
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: webapp
  cloud:
    azure:
      keyvault:
        secret:
          endpoint: https://uniquekeyvault1234.vault.azure.net/
          property-source-enabled: true
          property-sources[0]:
            endpoint: https://uniquekeyvault1234.vault.azure.net/
