name: Creates the azure infra via terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_TERRAFORM_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Plan
        run: terraform plan -var="my_ip=`$(curl -s https://api.ipify.org)`"
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="my_ip=`$(curl -s https://api.ipify.org)`"
        working-directory: infra